//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// K1.
    /// </summary>
    //  *** Start programmer edit section *** (K1 CustomAttributes)

    //  *** End programmer edit section *** (K1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("K1E", new string[0])]
    [View("K1L", new string[0])]
    public class K1 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (K1 CustomMembers)

        //  *** End programmer edit section *** (K1 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "K1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View K1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("K1E", typeof(IIS.mu2.K1));
                }
            }
            
            /// <summary>
            /// "K1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View K1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("K1L", typeof(IIS.mu2.K1));
                }
            }
        }
    }
}
